config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products
  resources :distributors
  resources :manufacturers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/distributor.rb
class Distributor < ApplicationRecord
    has_many :products
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
    has_one :product
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :manufacturer
    belongs_to :distributor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/distributors_controller.rb
class DistributorsController < ApplicationController
  before_action :set_distributor, only: [:show, :edit, :update, :destroy]

  # GET /distributors
  # GET /distributors.json
  def index
    @distributors = Distributor.all
  end

  # GET /distributors/1
  # GET /distributors/1.json
  def show
  end

  # GET /distributors/new
  def new
    @distributor = Distributor.new
  end

  # GET /distributors/1/edit
  def edit
  end

  # POST /distributors
  # POST /distributors.json
  def create
    @distributor = Distributor.new(distributor_params)

    respond_to do |format|
      if @distributor.save
        format.html { redirect_to @distributor, notice: 'Distributor was successfully created.' }
        format.json { render :show, status: :created, location: @distributor }
      else
        format.html { render :new }
        format.json { render json: @distributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /distributors/1
  # PATCH/PUT /distributors/1.json
  def update
    respond_to do |format|
      if @distributor.update(distributor_params)
        format.html { redirect_to @distributor, notice: 'Distributor was successfully updated.' }
        format.json { render :show, status: :ok, location: @distributor }
      else
        format.html { render :edit }
        format.json { render json: @distributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /distributors/1
  # DELETE /distributors/1.json
  def destroy
    @distributor.destroy
    respond_to do |format|
      format.html { redirect_to distributors_url, notice: 'Distributor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_distributor
      @distributor = Distributor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def distributor_params
      params.require(:distributor).permit(:name, :country)
    end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  before_action :set_manufacturer, only: [:show, :edit, :update, :destroy]

  # GET /manufacturers
  # GET /manufacturers.json
  def index
    @manufacturers = Manufacturer.all
  end

  # GET /manufacturers/1
  # GET /manufacturers/1.json
  def show
  end

  # GET /manufacturers/new
  def new
    @manufacturer = Manufacturer.new
  end

  # GET /manufacturers/1/edit
  def edit
  end

  # POST /manufacturers
  # POST /manufacturers.json
  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    respond_to do |format|
      if @manufacturer.save
        format.html { redirect_to @manufacturer, notice: 'Manufacturer was successfully created.' }
        format.json { render :show, status: :created, location: @manufacturer }
      else
        format.html { render :new }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manufacturers/1
  # PATCH/PUT /manufacturers/1.json
  def update
    respond_to do |format|
      if @manufacturer.update(manufacturer_params)
        format.html { redirect_to @manufacturer, notice: 'Manufacturer was successfully updated.' }
        format.json { render :show, status: :ok, location: @manufacturer }
      else
        format.html { render :edit }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufacturers/1
  # DELETE /manufacturers/1.json
  def destroy
    @manufacturer.destroy
    respond_to do |format|
      format.html { redirect_to manufacturers_url, notice: 'Manufacturer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manufacturer
      @manufacturer = Manufacturer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manufacturer_params
      params.require(:manufacturer).permit(:name, :country, :date_of_foundation)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :manufacturer_id, :distributor_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/distributors_helper.rb
module DistributorsHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/distributors/_form.html.erb
<%= form_with(model: distributor, local: true) do |form| %>
  <% if distributor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(distributor.errors.count, "error") %> prohibited this distributor from being saved:</h2>

      <ul>
        <% distributor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/distributors/edit.html.erb
<h1>Editing Distributor</h1>

<%= render 'form', distributor: @distributor %>

<%= link_to 'Show', @distributor %> |
<%= link_to 'Back', distributors_path %>

app/views/distributors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Distributors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @distributors.each do |distributor| %>
      <tr>
        <td><%= distributor.name %></td>
        <td><%= distributor.country %></td>
        <td><%= link_to 'Show', distributor %></td>
        <td><%= link_to 'Edit', edit_distributor_path(distributor) %></td>
        <td><%= link_to 'Destroy', distributor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Distributor', new_distributor_path %>

app/views/distributors/new.html.erb
<h1>New Distributor</h1>

<%= render 'form', distributor: @distributor %>

<%= link_to 'Back', distributors_path %>

app/views/distributors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @distributor.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @distributor.country %>
</p>

<%= link_to 'Edit', edit_distributor_path(@distributor) %> |
<%= link_to 'Back', distributors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Products</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <ul>
    <li><%= link_to "Виробники", manufacturers_path %></li>
    <li><%= link_to "Продукти", products_path %></li>
    <li><%= link_to "Продавці", distributors_path %></li>
  </ul>
    <%= yield %>
  </body>
</html>

app/views/manufacturers/_form.html.erb
<%= form_with(model: manufacturer, local: true) do |form| %>
  <% if manufacturer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manufacturer.errors.count, "error") %> prohibited this manufacturer from being saved:</h2>

      <ul>
        <% manufacturer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :date_of_foundation %>
    <%= form.date_select :date_of_foundation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/manufacturers/edit.html.erb
<h1>Editing Manufacturer</h1>

<%= render 'form', manufacturer: @manufacturer %>

<%= link_to 'Show', @manufacturer %> |
<%= link_to 'Back', manufacturers_path %>

app/views/manufacturers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manufacturers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th>Date of foundation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manufacturers.each do |manufacturer| %>
      <tr>
        <td><%= manufacturer.name %></td>
        <td><%= manufacturer.country %></td>
        <td><%= manufacturer.date_of_foundation %></td>
        <td><%= link_to 'Show', manufacturer %></td>
        <td><%= link_to 'Edit', edit_manufacturer_path(manufacturer) %></td>
        <td><%= link_to 'Destroy', manufacturer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manufacturer', new_manufacturer_path %>

app/views/manufacturers/new.html.erb
<h1>New Manufacturer</h1>

<%= render 'form', manufacturer: @manufacturer %>

<%= link_to 'Back', manufacturers_path %>

app/views/manufacturers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @manufacturer.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @manufacturer.country %>
</p>

<p>
  <strong>Date of foundation:</strong>
  <%= @manufacturer.date_of_foundation %>
</p>

<%= link_to 'Edit', edit_manufacturer_path(@manufacturer) %> |
<%= link_to 'Back', manufacturers_path %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :manufacturer_id %>
    <%= form.number_field :manufacturer_id %>
  </div>

  <div class="field">
    <%= form.label :distributor_id %>
    <%= form.number_field :distributor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Manufacturer</th>
      <th>Distributor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.manufacturer_id %></td>
        <td><%= product.distributor_id %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @product.manufacturer_id %>
</p>

<p>
  <strong>Distributor:</strong>
  <%= @product.distributor_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>